//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarvis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jarvis_DBEntities : DbContext
    {
        public Jarvis_DBEntities()
            : base("name=Jarvis_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conversation> Conversations { get; set; }
        public virtual DbSet<log_Grammar> log_Grammar { get; set; }
        public virtual DbSet<log_Jarvis> log_Jarvis { get; set; }
        public virtual DbSet<MLGrammar> MLGrammars { get; set; }
        public virtual DbSet<Response> Responses { get; set; }
    }
}
